// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/resume": {
    params: {};
  };
  "/setup": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/interviews": {
    params: {};
  };
  "/interviews/:interviewId": {
    params: {
      "interviewId": string;
    };
  };
  "/interview/:interviewId": {
    params: {
      "interviewId": string;
    };
  };
  "/interview/:interviewId/feedback": {
    params: {
      "interviewId": string;
    };
  };
  "/jobs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/resume" | "/setup" | "/account" | "/interviews" | "/interviews/:interviewId" | "/interview/:interviewId" | "/interview/:interviewId/feedback" | "/jobs";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/resume.tsx": {
    id: "routes/resume";
    page: "/resume";
  };
  "routes/protected.tsx": {
    id: "routes/protected";
    page: "/" | "/setup" | "/account" | "/interviews" | "/interviews/:interviewId" | "/interview/:interviewId" | "/interview/:interviewId/feedback" | "/jobs";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/setup.tsx": {
    id: "routes/setup";
    page: "/setup";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account";
  };
  "routes/interviews.tsx": {
    id: "routes/interviews";
    page: "/interviews" | "/interviews/:interviewId";
  };
  "routes/interviews._index.tsx": {
    id: "routes/interviews._index";
    page: "/interviews";
  };
  "routes/InterviewFeedback.tsx": {
    id: "routes/InterviewFeedback";
    page: "/interviews/:interviewId";
  };
  "routes/interview.tsx": {
    id: "routes/interview";
    page: "/interview/:interviewId";
  };
  "routes/feedback.tsx": {
    id: "routes/feedback";
    page: "/interview/:interviewId/feedback";
  };
  "routes/jobs/layout.tsx": {
    id: "routes/jobs/layout";
    page: "/jobs";
  };
  "routes/jobs/search.tsx": {
    id: "routes/jobs/search";
    page: "/jobs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/resume": typeof import("./app/routes/resume.tsx");
  "routes/protected": typeof import("./app/routes/protected.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/setup": typeof import("./app/routes/setup.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/interviews": typeof import("./app/routes/interviews.tsx");
  "routes/interviews._index": typeof import("./app/routes/interviews._index.tsx");
  "routes/InterviewFeedback": typeof import("./app/routes/InterviewFeedback.tsx");
  "routes/interview": typeof import("./app/routes/interview.tsx");
  "routes/feedback": typeof import("./app/routes/feedback.tsx");
  "routes/jobs/layout": typeof import("./app/routes/jobs/layout.tsx");
  "routes/jobs/search": typeof import("./app/routes/jobs/search.tsx");
};